### ISSUE TITLE
Repeat notifications disabling.

### ISSUE THREAD

**Issue by QuantumInformation** [RoccoC/webpack-build-notifier#11]
Sometimes when running with webpack a build will happen several times, when using `webpack --watch --watch-poll`. Is there a way to force this plugin to only give 1 notification until only a file change makes a build again?

**Comment by RoccoC** [comment]
Will setting `suppressSuccess` to `true` accomplish what you want? This will prevent successive notifications from appearing for successful builds. I am not sure how it will behave with `--wath-poll`, however I would assume that if the build has errors you will see an error notification for each failure each time webpack builds...

**Comment by RoccoC** [comment]
Closing for now. @QuantumInformation , re-open if you still have an issue, or feel free to submit a PR. :)
