### ISSUE TITLE
Just did fresh install - version with warning sound not installed..

### ISSUE THREAD

**Issue by codeuniquely** [RoccoC/webpack-build-notifier#14]
Can we bump the npm version number by 0.0.1 in package.json to make sure that we get the version with the configurable warning sound, when we install.

This code that is actually pulled from npm for '0.1.13' is this: 

```
this.sound = cfg.hasOwnProperty('sound') ? cfg.sound : 'Submarine';
this.successSound = cfg.hasOwnProperty('successSound') ? cfg.successSound : this.sound;
this.failureSound = cfg.hasOwnProperty('failureSound') ? cfg.failureSound : this.sound;
this.suppressSuccess = cfg.suppressSuccess || false;
```

but was expecting the additional code to be included (as per gitHub)
https://github.com/RoccoC/webpack-build-notifier/blob/master/index.js

```
this.sound = cfg.hasOwnProperty('sound') ? cfg.sound : 'Submarine';
this.successSound = cfg.hasOwnProperty('successSound') ? cfg.successSound : this.sound;
this.warningSound = cfg.hasOwnProperty('warningSound') ? cfg.warningSound : this.sound;
this.failureSound = cfg.hasOwnProperty('failureSound') ? cfg.failureSound : this.sound;
this.suppressSuccess = cfg.suppressSuccess || false;
```

The comments in each code section have been removed for brevity ...

**Comment by RoccoC** [comment]
@codeuniquely , thanks for pointing this out...looks like we forgot to bump the version when that new config option was added. Fixed.
