### ISSUE TITLE
suppressSuccess — ability to suppress notification after first run

### ISSUE THREAD

**Issue by develar** [RoccoC/webpack-build-notifier#17]
> Note that the success notification will always be shown for the first successful compilation or following a failed build regardless of the value of this setting.

I am working to integrate this excellent (because opposite to alternatives, icons are shown correctly) into electron-webpack. 

```
suppressSuccess: true
```

Use case: run `yarn dev` (run webpak-dev-server / webpack in a watch mode).

Expected: no success notification. Expected only if first successful compilation or following a failed build. I don't want to show notification if all is ok (first run). Only errors/warnings make sense.

**Comment by RoccoC** [comment]
@develar, thanks for submitting. Just so I understand, are you asking for the ability to completely suppress the success notifications, even in the case of first success after a failure, first run, etc?

**Comment by develar** [comment]
I want to see success notification only when it makes sense.

In my use case, run app in a development mode:

* On start, `yarn dev`, 2 parts are compiled. Success notification not needed because it is clear — app will be or started (window opened), or will be failure notification. In this case success notification will be just annoying.
* During run (watch mode), no need to notify about success — app works (assume that HMR/reloading work and no need to debug "was compilation triggered and changes applied?"). But should be success notification after failure —  to indicate, that compilation problem was fixed.

**Comment by RoccoC** [comment]
Thanks for the clarification. At present, when the `suppressSuccess` config option is set to *true*, the success  notification will still appear when compilation is first successful and each time after compilation succeeds following a compilation error.

Based on your previous comment (https://github.com/RoccoC/webpack-build-notifier/issues/17#issuecomment-317159474), I can make a change to support _not showing_ the success notification on first compilation/startup. I was thinking of modifying the `suppressSuccess` config option to accept a value of *initial*, which would behave the same as *true* but would also prevent the success notification from showing for the initial compilation. What do you think?

**Comment by develar** [comment]
> which would behave the same as true but would also prevent the success notification from showing for the initial compilation. What do you think?

Not clear for me why `suppressSuccess=true` doesn't really suppress :) A little bitcounterintuitive for me. But as it will be a  breaking change and you are more "in a context", I like `initial` option value as a solution. Thanks.

**Comment by RoccoC** [comment]
> Not clear for me why suppressSuccess=true doesn't really suppress

Yeah, I understand. Like you mentioned, the main reason I didn't want to change that behavior is to introduce a "breaking" change. I will make the change to add `initial` and maybe an `always` option and will update the docs as well. Thanks!

**Comment by RoccoC** [comment]
I've updated to add the `initial` and `always` options as discussed. Unfortunately not the most intuitive, but by setting `supressSuccess: "initial"` you should get the behavior you are after.

**Comment by develar** [comment]
@RoccoC Thanks a lot. Works as expected.
