### ISSUE TITLE
Feature request: init notification

### ISSUE THREAD

**Issue by jimblue** [RoccoC/webpack-build-notifier#19]
Hello!

First thank you so much for this very nice plugin, I love it !

I have a feature request to improve the experience while building.

It could be nice to have a notification on save as build process just start.
This feedback should give a nice responsiveness feeling but also would informe user about a potential problem.

Also a switch to activate this feature or not should be create.

And you could even add a new icon, maybe something like this:

![reload](https://user-images.githubusercontent.com/10623367/31975100-4863ec7c-b92f-11e7-9e38-798d90bb5b6a.png)

What do you think about this ? 😄

**Comment by RoccoC** [comment]
Hi @jimblue, thanks for the feature request!

Yes, I could see this as being useful, and with a toggle to enable this functionality (disabled by default?) it would not create a bunch of noise for those who do not want the extra notifications.

Do you want to have a go at adding the feature and creating a PR? :)

**Comment by jimblue** [comment]
Yes disable by default make sens for old user.

I know scss and twig a bit but js... sorry

**Comment by RoccoC** [comment]
@jimblue , I've added this feature in commit d9a2c88 for version 0.1.17. You can enable by passing `suppressCompileStart: false` to the plugin options. Let me know how it goes!

**Comment by jimblue** [comment]
Working like a charm! Thank you so much, it's very nice 👍
