### ISSUE TITLE
iTerm2 support

### ISSUE THREAD

**Issue by saiichihashimoto** [RoccoC/webpack-build-notifier#21]
I'm currently using [iTerm2](https://www.iterm2.com/) rather than terminal and both the `activateTerminalOnError` and `onClick` opens a new Terminal (not ideal).

So two questions:

- Can iTerm2 be supported by default? And, if not,
- What's the quickest path to me solving this in my own project (ie is there a parameter for which application gets opened that I can change)?

**Comment by saiichihashimoto** [comment]
Keeping in mind that my coworkers *don't* use iTerm2 and use the default Terminal.

**Comment by saiichihashimoto** [comment]
Keeping in mind that my coworkers *don't* use iTerm2 and use the default Terminal.

**Comment by RoccoC** [comment]
We can fix this. Definitely should add a config option (or somehow figure out the spawning app) rather than hardcode to terminal.

**Comment by saiichihashimoto** [comment]
That would be great! It would be ideal if it detected which one so the command could work for all of us!
