### ISSUE TITLE
Notification gone after Mac update

### ISSUE THREAD

**Issue by Luckyfella73** [RoccoC/webpack-build-notifier#23]
Hi,

after updating my macbook to High Sierra 10.13.4 (from 10.13.3) and upgrading to command line tools 9.3 (from 9.2) I don't get any notifications anymore - no sound and no notice (in the right top corner of the screen). Yesterday (before upgrading) it worked fine and I didn't install anything else. I get no error message in terminal and changes I make in the code are processed by webpack.

Any ideas what to do about this?

**Comment by RoccoC** [comment]
I have yet to update to High Sierra 10.13.4 -- I will update and see what I can find out.

**Comment by jimblue** [comment]
Can't reproduce problem @Luckyfella73 with the same config:

webpack 4.6
webpack-build-notifier 0.1.23
Mac OS X 10.13.4
CLTools 9.3

**Comment by Luckyfella73** [comment]
@jimblue thanks for testing. Could you check once more using `"webpack": "^3.11.0"` in package.json ? I didn't switch to webpack 4.x yet.

**Comment by RoccoC** [comment]
No worries, @Luckyfella73. Glad you got it sorted out!
