### ISSUE TITLE
Make the new note-notifier options configurable.

### ISSUE THREAD

**Issue by ntavelis** [RoccoC/webpack-build-notifier#26]
Hello,

Thank you for this package. Would it be possible to make the new note-notifier options configurable from this package ?

 // New in latest version. See `example/macInput.js` for usage
    timeout: 5, // Takes precedence over wait if both are defined.
    closeLabel: void 0, // String. Label for cancel button
    actions: void 0, // String | Array<String>. Action label or list of labels in case of dropdown
    dropdownLabel: void 0, // String. Label to be used if multiple actions
    reply: false // Boolean. If notification should take input. Value passed as third argument in callback and event emitter.

notifier.on('timeout', function(notifierObject, options) {
  // Triggers if `wait: true` and notification closes
});

An idea, perhaps merge the user configuration with the defaults so that in the future we can pass any new options without the need for a new release. Something like `Object.assign({}, defaultConfig, userConfig);`

**Comment by RoccoC** [comment]
Hi there, thanks for the request. I do agree with your suggestion to accommodate a notifier config object and will have a look at updating this plugin in the next couple of days. 👍

**Comment by RoccoC** [comment]
Although looks like you've already created your own here: https://github.com/ntavelis/webpack-build-notifications

Why not submit a PR?

**Comment by ntavelis** [comment]
Yeah, I was experimenting with the web pack lately. Basically I made a number of changes that I wasn't sure that would be OK with you.

That being said, this package uses your library. https://github.com/ntavelis/pretty-mix-notifications

Do you want me to make a PR here? If the changes are fine to you, there will be no need to maintain and the package you mentioned

**Comment by RoccoC** [comment]
@ntavelis, I've updated webpack-build-notifier to now accept `onTimeout` and `notifyOptions` as new config options. Please try out v0.1.26 and let me know if you have any questions or issues. Thanks again! 👍

**Comment by ntavelis** [comment]
Thank you! I will test it and let you know.
