### ISSUE TITLE
Different sound for error / success

### ISSUE THREAD

**Issue by martinlindhe** [RoccoC/webpack-build-notifier#3]
I'm trying to figure out how/if possible to have 

on success: popup, play Submarine sound (the default)
on fail: popup, play Basso sound (errorish beep)

this would also be fine:
on success: popup, silent
on fail: popup, play Basso sound

the thing is i want a popup even on success (to see my tool was run),
so i cant exactly set the Basso sound and `alwaysNotify: false`

any ideas?

**Comment by RoccoC** [comment]
Unfortunately, setting a different sound for errors vs warnings isn't supported at the moment, but it would be very easy to implement. I can make the change sometime today.

**Comment by RoccoC** [comment]
@martinlindhe , I've added two new config options to allow specifying of different sounds for success vs failure. These are available in v0.1.8.

You can accomplish what you want by passing `failureSound: "Basso"` in the WebpackBuildNotifier config. The notifier will then play the default sound on success and "Basso" for errors and warnings.

Thanks for the sugestion!

**Comment by martinlindhe** [comment]
Wow! very nice, i can conform it working :-)
