### ISSUE TITLE
Compilation notification sound cannot be changed/disabled.

### ISSUE THREAD

**Issue by DocCoding** [RoccoC/webpack-build-notifier#30]
The 'compileStart' notification has a sound even if the `sound` option is set to `false`.

It seems it is not affected by the `sound` option in general, and it has no option on its own.

**Comment by DocCoding** [comment]
@RoccoC Possibly add the `bug` label to this issue, since I think it is one.

**Comment by RoccoC** [comment]
Fair enough, added the bug label and merged your PR. Thanks!
