### ISSUE TITLE
Add Unit Tests and CI

### ISSUE THREAD

**Issue by RoccoC** [RoccoC/webpack-build-notifier#32]
At present this project has no unit tests or continuous integration checks. Would be nice to add some!

**Comment by saurabhnemade** [comment]
@RoccoC Hope this helps.

PR #33 is added. Very basic test cases with jest are added. Couldn't find a way to test compiler options yet however test case with full webpack build is added.

For Travis CI Configuration:
- Currently it will simply build and send email.

Auto Deploy configuration can also be done with following added to .travis.yml

```
deploy:
- provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
```

In case, you want to add deploy configuration, $NPM_EMAIL and $NPM_TOKEN need to configured in travis ci under project settings. This deploy configuration can deploy only on master branch. All other branches it will just build.
(Example .travis.yml with both build and deploy: https://github.com/saurabhnemade/react-twitter-embed/blob/master/.travis.yml)

Similarly, you can also configure another variable $NOTIFICATION_EMAIL in travis ci settings to mask email from .travis.yml file.

**Comment by RoccoC** [comment]
@saurabhnemade , thank you, this is great! I will review today. Thanks again for your help with this!

**Comment by RoccoC** [comment]
PR merged! Thanks again for the help with this. ;)
