### ISSUE TITLE
[FR] provide access to timeout option

### ISSUE THREAD

**Issue by jimblue** [RoccoC/webpack-build-notifier#34]
Hi,

Node notifications are displayed by default for 5s long seconds and that can be annoying.
It seems that node notifier have a **timeout** option to change that.

It could be nice to be able to access this settings from your plugin.

Cheers

**Comment by RoccoC** [comment]
Hi @jimblue,

You should be able to pass any `node-notifier` options as part of the `notifyOptions` config: https://github.com/RoccoC/webpack-build-notifier#notifyoptions

Can you give it a try and let me know if that doesn't work?

**Comment by jimblue** [comment]
Sorry didn't read the doc enough, it's working great :)

**Comment by RoccoC** [comment]
No worries, glad it worked out!

**Comment by ggedde** [comment]
@RoccoC 
Is it possible to do that for different types?
I would like the success to go away after 5 seconds, but errors stay on much longer.
