### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by muuvmuuv** [RoccoC/webpack-build-notifier#35]
What about a type definition for `webpack-build-notifier`? I would like to discuss if this makes sense for you. I'm using webpack with TypeScript and this would prevent me from creating a global.d.ts file with just `declare module 'webpack-build-notifier'` and helps me with typings.

**Comment by RoccoC** [comment]
Sure, that's a great idea.

There are a couple of options. We could manually define the project type definitions in a `d.ts` file, or convert the project over to TypeScript and let TS generate the definitions. I can pick this up in the next few days unless you were interested in tackling it? ;)

**Comment by muuvmuuv** [comment]
@RoccoC great! I tried it with no good result. I'm not very good at declaring types (still on my to do) and I think it's better you take on this as the person who knows exactly what which function/call does. :)

**Comment by muuvmuuv** [comment]
I would personally create an own Type Definition instead of letting TS does the job. It is good for a starting point but sometimes not ideal.

**Comment by RoccoC** [comment]
@muuvmuuv - created a PR for this, here: https://github.com/RoccoC/webpack-build-notifier/pull/36

**Comment by RoccoC** [comment]
PR merged.

**Comment by muuvmuuv** [comment]
Awesome!
