### ISSUE TITLE
onClick not working

### ISSUE THREAD

**Issue by ashrafhadden** [RoccoC/webpack-build-notifier#37]
- mac v10.14.4
-  webpack-build-notifier v0.1.31

The onClick config option is not working, it does nothing even with default setting which is supposed to open the Terminal app. Playing around with shelljs and child_process `exec` didn't work either. 

If you could verify that it's working and then also provide an implementation code example in the README, for example to run command `open http://localhost:8080/` which would open the localhost in browser. Thanks!

**Comment by RoccoC** [comment]
Thanks for the report. Will take a look!

**Comment by ashrafhadden** [comment]
@RoccoC Dunno if you did anything but it totally works now!

**Comment by RoccoC** [comment]
Awesome, glad to hear and thank you for letting me know! Must have been fixed by way of the recent node-notifier upgrade. ;)
