### ISSUE TITLE
chars instead of colors in windows 10 notification

### ISSUE THREAD

**Issue by gregoks** [RoccoC/webpack-build-notifier#5]
Hi,

In windows 10 it shows chars (37m([39m...) instead of what I assume colors:

![capture](https://cloud.githubusercontent.com/assets/15245808/16847073/cf41d310-49f7-11e6-86ae-5747c4088228.PNG)

Thanks,

Greg

**Comment by RoccoC** [comment]
@gregoks, thanks for the bug report. Turns out that this is an issue across platforms. Let me see if I can come up with a quick fix. :)

**Comment by RoccoC** [comment]
This should be fixed in the latest version, 0.1.10. Thanks again!

**Comment by gregoks** [comment]
worked like a charm! Thanks!
