### ISSUE TITLE
Sounds play when sound is false

### ISSUE THREAD

**Issue by bwoolnough** [RoccoC/webpack-build-notifier#51]
Setting sound to false doesn't prevent sounds from playing. It only works if I set the specific sound options (successSound etc) to false.

I am using macOS 10.15.2 and webpack-build-notifier 2.0.0.

**Comment by jimblue** [comment]
I can reproduce that bug on latest release too.
@RoccoC can you confirm that please ?
This bug is really annoying for development !
Tks man :)

**Comment by RoccoC** [comment]
Whoops, somehow this bug fell off my radar. This one is now fixed in `2.0.1`.

**Comment by jimblue** [comment]
No worries @RoccoC and thank you so much for the quick fix 💯
