### ISSUE TITLE
Doesn't seems to work on Apple Silicon with Big Sur using Webpack 5

### ISSUE THREAD

**Issue by jimblue** [RoccoC/webpack-build-notifier#63]
I'm not sure why it's not working @RoccoC... Apple Silicon ? Big Sur ? Wenbpack 5 ? All of them...

**Comment by jimblue** [comment]
My bad, sorry for the noise, seems to be because of node-notifier.

**Comment by RoccoC** [comment]
Hey @jimblue , thanks for the bug report. Yeah, could be -- I see there's an issue logged over there as well: https://github.com/mikaelbr/node-notifier/issues/361

Unfortunately I don't have an M1 to test with, but I'll do some digging to see if I can positively identify the source of the problem.

I'm going to re-open this so it doesn't fall off the radar.

**Comment by RoccoC** [comment]
@jimblue, by chance are you seeing the same error as reported in the `node-notifier` issue?

```
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:416:11)
    at spawn (node:child_process:619:9)
    at Object.execFile (node:child_process:262:17)
    at Object.module.exports.fileCommandJson (/node_modules/node-notifier/lib/utils.js:83:13)
```

**Comment by jimblue** [comment]
@RoccoC no I don't sorry

**Comment by GuidoHendriks** [comment]
@RoccoC I see the same error on my Mac mini M1. Please let me know if I can help out in any way.

**Comment by haxxxton** [comment]
not sure if related, but I just upgraded from webpack 4 to webpack 5, and latest build notifier has stopped working. (Intel chip)

**Comment by abigmiu** [comment]
intel core can be used with BigSur. But MacOS 12 with intel core not work。

**Comment by ImLunaHey** [comment]
This can be closed. Installing rosetta resolves this issue.
