### ISSUE TITLE
Not working on macOS Sierra

### ISSUE THREAD

**Issue by ahmedghoneim92** [RoccoC/webpack-build-notifier#8]
After upgrading to sierra, I re-installed the plugin to make sure it builds correctly. Still though, I get no notifications. The terminal activation option ( on error ) works though. How can I provide you with more information for this issue?
Thanks 😊

**Comment by RoccoC** [comment]
Perhaps an issue with the node-notifier package...I will upgrade my system to Sierra and will take a look. Thanks for the report.

**Comment by ahmedghoneim92** [comment]
Turns out it was something wrong at my side. Nevermind, thanks :)
