### ISSUE TITLE
Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by andrewdavidcostello** [RoccoC/webpack-build-notifier#9]
When an error is too long it causes Webpack to exit with:

`Error: spawn ENAMETOOLONG`

It would be good to have a max length of the raw output (and truncate it) or even better options for a custom message for warning and error as having the raw output in the error isn't too helpful anyway.

**Comment by RoccoC** [comment]
Thanks for the report.

Is this occurring on a Windows machine? I haven't come across this issue in OSX, and generally the notification messages I've seen always contain a filename and line number, which is helpful IMO.

That said, it would make sense to truncate the error since its length usually exceeds that which can be displayed in the notification, and support for custom messages would be useful.

**Comment by andrewdavidcostello** [comment]
Sorry thought I put that. Yep unfortunately stuck on Windows 10. Oh yeah sometimes they are handy but a lot of the errors we have been getting lately it may just be nicer to have the option to simplify the message, especially when there is more than one error.

Thanks.

**Comment by RoccoC** [comment]
Just to confirm, in the case when you see the `ENAMETOOLONG` error, does Webpack no longer exit if you remove the WebpackBuildNotifer plugin?

IIRC, Windows imposes a 260 char limit on file paths...not sure if this is still the case in Win10 or if this is even the cause of the error.

I tried to reproduce but was unable to. I'll get my hands on a Windows machine and try again though.

**Comment by andrewdavidcostello** [comment]
Yep if I remove it Webpack runs fine. The rest of the trace shows that it originates in the toast notification of Windows 10. I don't have my work machine with me right now but I will try and get more detail.

**Comment by RoccoC** [comment]
Great, thanks for the response. I'll take a closer look and will put together a fix soon. Thanks!

**Comment by RoccoC** [comment]
@andrewdavidcostello , I did some testing on my Windows machine and wasn't able to reproduce the ENAMETOOLONG issue that you describe. Do you have any deeply nested files in your project that could be resulting in a excessively long filepath?

In any case, the latest build, *0.1.13*, offers a messageFormatter configuration option to allow for custom notification message formatting. Could you try it out to see if it helps for your case?

Also, if you can come up with a reproduce case for the error please reopen this one and I can investigate further.

**Comment by andrewdavidcostello** [comment]
Since doing the Windows 10 anniversary update I can't seem to repro this anymore, however if it does occur again the messageFormatter is working perfectly so thanks for adding that.
